id: P77B79C69
initial_creation_type: input
source_metadata:
  title: Lhodrak Namkha Gyaltsen
  language: fr
  description: 'Texts by Lhodrak Namkha Gyaltsen (lho brag nam mkha'' rgyal mtshan,
    1326–1401), also known as Drupchen Lekyi Dorje (grub chen las kyi rdo rje), who
    was a teacher of Tsongkhapa Lobzang Drakpa:'
  volume:
    197851294de14b8d802c5adae9d564e2:
      title: Averting Obstacles through Sitātapatrā
      parent: Averting Obstacles
created_at: '2022-03-01T00:36:28.851415'
last_modified_at: '2022-03-01T00:36:28.851418'
